from __future__ import annotations

from app.crud.base import CRUDBase
from app.crud.crud_assignment import (
    CRUDAssignment,
    assignment,
    create_assignment,
    delete_assignment,
    get_assignment,
    get_assignments_by_context,
    update_assignment,
)
from app.crud.crud_enrollment import (
    CRUDEnrollment,
    CRUDStudentProgress,
    enrollment,
    student_progress,
)
from app.crud.crud_quiz import (
    CRUDQuestion,
    CRUDQuiz,
    create_question,
    create_quiz,
    delete_question,
    delete_quiz,
    get_question,
    get_questions_by_lesson,
    get_questions_by_track,
    get_quiz,
    question,
    quiz,
    update_question,
    update_quiz,
)
from app.crud.crud_role import role
from app.crud.crud_submission import (
    CRUDSubmission,
    create_submission,
    get_submission,
    get_submissions_by_assignment,
    get_submissions_by_user,
    review_submission,
    submission,
    update_submission,
)
from app.crud.crud_track import (
    CRUDLesson,
    CRUDResource,
    CRUDTrack,
    CRUDTrackModule,
    lesson,
    resource,
    track,
    track_module,
)
from app.crud.crud_user import user

__all__ = [
    "CRUDBase",
    "CRUDAssignment",
    "CRUDTrack",
    "CRUDTrackModule",
    "CRUDLesson",
    "CRUDResource",
    "CRUDEnrollment",
    "CRUDStudentProgress",
    "CRUDSubmission",
    "track",
    "track_module",
    "lesson",
    "resource",
    "enrollment",
    "student_progress",
    "assignment",
    "create_assignment",
    "get_assignment",
    "get_assignments_by_context",
    "update_assignment",
    "delete_assignment",
    "submission",
    "create_submission",
    "get_submission",
    "get_submissions_by_user",
    "get_submissions_by_assignment",
    "update_submission",
    "review_submission",
    "CRUDQuestion",
    "CRUDQuiz",
    "question",
    "quiz",
    "create_question",
    "get_question",
    "get_questions_by_track",
    "get_questions_by_lesson",
    "update_question",
    "delete_question",
    "create_quiz",
    "get_quiz",
    "update_quiz",
    "delete_quiz",
    "role",
    "user",
]
