from __future__ import annotations

from app.schemas.assignment import (
    AssignmentBase,
    AssignmentCreate,
    AssignmentResponse,
    AssignmentUpdate,
)
from app.schemas.enrollment import (
    Enrollment,
    EnrollmentCreate,
    EnrollmentDetail,
    EnrollmentUpdate,
    StudentProgress,
    StudentProgressCreate,
    StudentProgressDetail,
    StudentProgressUpdate,
)
from app.schemas.graduation import (
    GraduationEvaluationResponse,
    GraduationGateCheckResponse,
)
from app.schemas.project_submission import (
    ProjectReviewCreate,
    ProjectReviewResponse,
    ProjectSubmissionBase,
    ProjectSubmissionCreate,
    ProjectSubmissionResponse,
    ProjectSubmissionUpdate,
)
from app.schemas.quiz import (
    QuestionBase,
    QuestionCreate,
    QuestionOptionBase,
    QuestionOptionCreate,
    QuestionOptionResponse,
    QuestionResponse,
    QuestionUpdate,
    QuizBase,
    QuizCreate,
    QuizQuestionBase,
    QuizQuestionCreate,
    QuizQuestionResponse,
    QuizResponse,
    QuizUpdate,
)
from app.schemas.quiz_attempt import (
    QuizAnswerCreate,
    QuizAnswerResponse,
    QuizAttemptResponse,
    QuizAttemptSubmit,
)
from app.schemas.role import Role, RoleCreate, RoleUpdate
from app.schemas.submission import (
    SubmissionBase,
    SubmissionCreate,
    SubmissionDetailResponse,
    SubmissionResponse,
    SubmissionReview,
    SubmissionReviewCreate,
    SubmissionReviewResponse,
    SubmissionUpdate,
)
from app.schemas.token import Token, TokenPayload
from app.schemas.track import (
    Lesson,
    LessonCreate,
    Resource,
    ResourceCreate,
    Track,
    TrackCreate,
    TrackCurriculum,
    TrackModule,
    TrackModuleCreate,
    TrackSummary,
)
from app.schemas.track_assignment_config import (
    TrackAssignmentConfigResponse,
    TrackAssignmentConfigUpdate,
)
from app.schemas.user import User, UserCreate, UserInDB, UserUpdate

__all__ = [
    "AssignmentBase",
    "AssignmentCreate",
    "AssignmentUpdate",
    "AssignmentResponse",
    "SubmissionBase",
    "SubmissionCreate",
    "SubmissionUpdate",
    "SubmissionReview",
    "SubmissionReviewCreate",
    "SubmissionReviewResponse",
    "SubmissionResponse",
    "SubmissionDetailResponse",
    "QuestionOptionBase",
    "QuestionOptionCreate",
    "QuestionOptionResponse",
    "QuestionBase",
    "QuestionCreate",
    "QuestionUpdate",
    "QuestionResponse",
    "QuizQuestionBase",
    "QuizQuestionCreate",
    "QuizQuestionResponse",
    "QuizBase",
    "QuizCreate",
    "QuizUpdate",
    "QuizResponse",
    "QuizAnswerCreate",
    "QuizAnswerResponse",
    "QuizAttemptSubmit",
    "QuizAttemptResponse",
    "ProjectSubmissionBase",
    "ProjectSubmissionCreate",
    "ProjectSubmissionUpdate",
    "ProjectReviewCreate",
    "ProjectReviewResponse",
    "ProjectSubmissionResponse",
    "Role",
    "RoleCreate",
    "RoleUpdate",
    "Token",
    "TokenPayload",
    "User",
    "UserCreate",
    "UserInDB",
    "UserUpdate",
    "Resource",
    "ResourceCreate",
    "Lesson",
    "LessonCreate",
    "TrackModule",
    "TrackModuleCreate",
    "Track",
    "TrackCreate",
    "TrackSummary",
    "TrackCurriculum",
    "TrackAssignmentConfigResponse",
    "TrackAssignmentConfigUpdate",
    "Enrollment",
    "EnrollmentCreate",
    "EnrollmentUpdate",
    "EnrollmentDetail",
    "StudentProgress",
    "StudentProgressCreate",
    "StudentProgressUpdate",
    "StudentProgressDetail",
    "GraduationGateCheckResponse",
    "GraduationEvaluationResponse",
]
